name: syntech_nepali_calendar
description: "A Dart library for handling Nepali calendar dates, conversions, and formatting."
version: 1.0.1
repository: https://github.com/GurungNabin/syntech-nepali-calendar

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.17.0"

# Add regular dependencies here.
dependencies:
  flutter: 
    sdk: flutter

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
